version: '2'
services:

  node-external-apvs:
    build: .
    volumes:
      - "./build.sh:/usr/src/app/build.sh"
      - "./app:/usr/src/app/app"
      - "./cache_node_modules:/usr/src/app/node_modules"
    ports:
      - "3000:3000"